import { useEffect,useState,type FormEvent } from 'react'
import { api,type CrmCompany } from '../lib/crm'
export default function CompanyDetails({id,onClose,onSaved}:{id:string;onClose:()=>void;onSaved:()=>void}) {
  const [data,setData]=useState<{company:CrmCompany;contacts:{id:string;name:string}[];leads:{id:string;title:string}[]}>()
  const [form,setForm]=useState({name:'',cnpj:'',domain:'',phone:'',email:'',address:''})
  const [error,setError]=useState('')
  const [busy,setBusy]=useState(false)
  useEffect(()=>{let active=true;api<NonNullable<typeof data>>(`/api/companies/${id}`).then(r=>{if(!active)return;setData(r);setForm({name:r.company.name,cnpj:r.company.cnpj??'',domain:r.company.domain??'',phone:r.company.phone??'',email:r.company.email??'',address:r.company.address??''})}).catch(e=>active&&setError(e.message));return()=>{active=false}},[id])
  async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api(`/api/companies/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(Object.entries(form).map(([k,v])=>[k,v||null])))});onSaved();onClose()}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar.')}finally{setBusy(false)}}
  return <div className="fixed inset-0 z-50 overflow-auto bg-black/40 p-4"><form role="dialog" aria-modal="true" aria-label="Ficha da empresa" onSubmit={save} className="mx-auto my-6 max-w-xl space-y-3 rounded-xl bg-white p-6"><div className="flex justify-between"><h3 className="font-semibold">Ficha da empresa</h3><button type="button" onClick={onClose}>Fechar</button></div>{error&&<p role="alert" className="text-red-700">{error}</p>}{!data&&!error&&<p>Carregando empresa...</p>}{data&&<>{(['name','cnpj','domain','phone','email','address']as const).map((k,i)=><label key={k} className="block text-sm">{['Nome','CNPJ','Site','Telefone','E-mail','Endereço'][i]}<input required={k==='name'} type={k==='email'?'email':'text'} className="mt-1 block w-full rounded border p-2" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<h4 className="font-semibold">Contatos vinculados</h4>{data.contacts.length?data.contacts.map(c=><p className="text-sm" key={c.id}>{c.name}</p>):<p className="text-sm text-slate-500">Nenhum contato vinculado.</p>}<h4 className="font-semibold">Oportunidades</h4>{data.leads.length?data.leads.map(l=><p className="text-sm" key={l.id}>{l.title}</p>):<p className="text-sm text-slate-500">Nenhuma oportunidade vinculada.</p>}<button disabled={busy} className="rounded bg-blue-600 px-4 py-2 text-white">{busy?'Salvando...':'Salvar empresa'}</button></>}</form></div>
}
